function Hd = FIR_LP_cLS
%FIR_LP_CLS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 27-Feb-2020 14:51:16

% FIR constrained least-squares Lowpass filter designed using the FIRCLS
% function.

% All frequency values are in kHz.
Fs = 80;  % Sampling Frequency

N      = 6;    % Order
Fc     = 2.5;  % Cutoff Frequency
DpassU = 0.1;  % Upper Passband Ripple
DpassL = 0.1;  % Lower Passband Ripple
DstopU = 0.1;  % Upper Stopband Attenuation
DstopL = 0.1;  % Lower Stopband Attenuation

% Calculate the coefficients using the FIRCLS function.
b  = fircls(N, [0 Fc Fs/2]/(Fs/2), [1 0], [1+DpassU DstopU], [1-DpassL ...
            -DstopL]);
Hd = dfilt.dffir(b);

% [EOF]
