function Hd = FIR_LP_LS
%FIR_LP_LS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 27-Feb-2020 14:50:30

% FIR least-squares Lowpass filter designed using the FIRLS function.

% All frequency values are in kHz.
Fs = 80;  % Sampling Frequency

N     = 6;     % Order
Fpass = 2.5;   % Passband Frequency
Fstop = 3;     % Stopband Frequency
Wpass = 0.2;   % Passband Weight
Wstop = 0.25;  % Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop]);
Hd = dfilt.dffir(b);

% [EOF]
