function Hd = FIR_LP_equiripple
%FIR_LP_EQUIRIPPLE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 27-Feb-2020 14:50:12

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 80;  % Sampling Frequency

N     = 6;    % Order
Fpass = 2.5;  % Passband Frequency
Fstop = 3;    % Stopband Frequency
Wpass = 0.2;  % Passband Weight
Wstop = 1;    % Stopband Weight
dens  = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd = dfilt.dffir(b);

% [EOF]
