function Hd = IIR_LP_CHEBSHEVT2_new
%IIR_LP_CHEBSHEVT2_NEW Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 12-Mar-2020 17:37:02

% Chebyshev Type II Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in kHz.
Fs = 160;  % Sampling Frequency

N     = 6;   % Order
Fstop = 6;   % Stopband Frequency
Astop = 80;  % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.lowpass('N,Fst,Ast', N, Fstop, Astop, Fs);
Hd = design(h, 'cheby2');

% [EOF]
