function Hd = IIR_LP_Max_flat
%IIR_LP_MAX_FLAT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 27-Feb-2020 14:49:55

% IIR maximally flat Lowpass filter designed using the MAXFLAT function.

% All frequency values are in kHz.
Fs = 80;  % Sampling Frequency

Nb   = 6;    % Numerator Order
Na   = 6;    % Denominator Order
F3dB = 2.5;  % 3-dB Frequency

h  = fdesign.lowpass('Nb,Na,F3dB', Nb, Na, F3dB, Fs);
Hd = design(h, 'butter');

% [EOF]
